name: Gradle Build
on: [push, pull_request]

jobs:
  build:
    name: Build WorldEdit on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup permission to execute gradle
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew worldedit-bukkit:build -s
    - uses: actions/upload-artifact@v2
      name: Archive Reports
      if: always()
      with:
        name: reports for ${{ matrix.os }}
        path: '**/build/reports/**'
    - uses: actions/upload-artifact@v2
      name: Upload bukkit jar
      if: always()
      with:
        name: Worldedit build with ${{ matrix.os }}
        path: '**/build/libs/**'
